document.addEventListener("DOMContentLoaded", function () {
    document.getElementById("excuse").innerText = generatorDate();

    document.getElementById("neon").addEventListener("click", function () {
        document.getElementById("excuse").innerText = generatorDate();
    });
});


var generatedDate = [];

function generatorDate() {
    var beauf = [
        "Hé, jolies jambes. Elles ouvrent à quelle heure ?",
        "Ton corps doit être une carte au trésor, parce que je veux bien me perdre dessus.",
        "Si tu étais un légume, tu serais une cochonne.",
        "Je te donnerais bien une fessée, mais je ne voudrais pas te donner du plaisir.",
        "Ma chambre est en désordre, tu viens faire le ménage ?",
        "Tu ferais une bonne actrice porno, t'as le physique pour.",
        "Les bonnes filles vont au paradis, les mauvaises vont chez moi.",
        "Tes vêtements iraient mieux par terre.",
        "T'es tellement belle que tu me fais oublier ma femme.",
        "Je parie que tu serais mieux sans vêtements.",
        "Ton corps crie pour du sexe, ça tombe bien, je suis disponible.",
        "Je suis prêt à te payer une chambre pour qu'on règle ça.",
        "Tu devrais sourire plus, tu serais plus jolie.",
        "C'est quoi ton tarif pour une nuit ?",
        "Je pourrais te regarder toute la journée, mais je préfère te toucher.",
        "J'ai une place dans mon lit, ça te dit de l'occuper ?",
        "Tu veux voir ma collection de conquêtes ?",
        "Avec un corps comme le tien, tu n'as pas besoin d'avoir de personnalité.",
        "Tu es comme une carte de crédit, toujours prête à être utilisée.",
        "Viens chez moi et je te montrerai comment les vrais hommes traitent les femmes.",
        "J'ai envie de toi maintenant, tu fais quoi ce soir ?",
        "Tu as l'air d'une bonne cuisinière, tu pourrais préparer quelque chose pour moi ?",
        "Je parie que tu es super ennuyeuse, mais ça ne fait rien, je veux juste ton corps.",
        "Avec un physique comme le tien, pas besoin d'être intelligente.",
        "Les filles comme toi, ça s'attrape facilement.",
        "T'es une vraie bombe, je me demande combien de mecs tu as déjà fait exploser.",
        "T'as des talents cachés ? Viens les montrer chez moi.",
        "Je te mettrais bien dans mon lit pour voir ce que tu sais faire.",
        "Je suis un vrai mec, et toi une vraie femme, ça se voit.",
        "Les femmes comme toi, ça se prend sans réfléchir.",
        "Tu devrais être fière de te faire draguer par un mec comme moi.",
        "T'as un cul à rendre jaloux un Kardashian.",
        "Je te donnerais bien une claque sur le cul, mais t'aimerais trop ça.",
        "On dirait que t'as besoin d'un vrai homme dans ta vie.",
        "Les femmes sont faites pour plaire aux hommes, et tu fais bien ton boulot.",
        "Je te ferais bien l'amour toute la nuit, mais j'ai pas autant de temps à perdre.",
        "T'es bonne, mais je préfère quand même ta copine.",
        "Un sourire, c'est gratuit, alors fais-en un.",
        "Je te prendrais bien pour un tour, mais juste un tour.",
        "Les femmes comme toi, ça se mérite, et je suis prêt à te mériter.",
        "Je suis sûr que tu ferais une excellente maîtresse de maison.",
        "Avec un corps comme le tien, je te pardonne ton cerveau.",
        "Je te ferais bien découvrir ce que c'est qu'un vrai homme.",
        "Tu dois être fatiguée de courir dans la tête de tous les mecs.",
        "Je te mettrais bien dans mon lit et dans ma vie, mais surtout dans mon lit.",
        "Si tu étais une récompense, je travaillerais dur pour t'avoir.",
        "Je te donnerais bien une leçon de vie, mais surtout de lit.",
        "Les filles comme toi, ça se prend et ça se jette.",
        "Je suis prêt à te faire des choses que tu n'as jamais osé imaginer.",
        "Je suis sûr que tu ferais une excellente addition à mon tableau de chasse.",
        "Avec des jambes comme les tiennes, tu dois être une excellente marcheuse... vers mon lit.",
        "Je ne cherche pas une relation, juste une bonne nuit.",
        "Ton corps crie sexe, ça tombe bien, j'ai des oreilles pour l'entendre.",
        "Viens chez moi, je te montrerai ce que c'est que d'être une femme.",
        "Les femmes comme toi, ça se garde pour une nuit.",
        "Je suis sûr que tu es aussi bonne au lit que tu en as l'air.",
        "Je te mettrais bien dans mon lit, mais pas dans mon cœur.",
        "Tu es tellement belle que je pourrais te regarder toute la nuit, mais je préfère te toucher.",
        "Je te donnerais bien une chance de prouver que tu n'es pas qu'une jolie fille.",
        "Les femmes sont faites pour plaire aux hommes, et tu fais du bon boulot.",
        "Je suis sûr que tu es aussi sauvage au lit que tu en as l'air.",
        "Je te mettrais bien dans mon lit pour voir si tu es à la hauteur de tes courbes.",
        "Avec un corps comme le tien, tu n'as pas besoin de cerveau.",
        "Les filles comme toi, ça se drague facilement.",
        "Tu ferais une bonne addition à ma liste de conquêtes.",
        "Je suis prêt à te faire des choses que tu n'as jamais imaginées.",
        "Je suis sûr que tu es aussi chaude au lit que tu en as l'air.",
        "Je te donnerais bien une fessée pour voir si tu aimes ça.",
        "Je suis prêt à te montrer ce que c'est qu'un vrai homme.",
        "Tu ferais une bonne addition à ma collection de conquêtes.",
        "Avec un corps comme le tien, tu n'as pas besoin d'être intelligente.",
        "Tu dois être fatiguée, parce que tu cours dans mes pensées toute la journée.",
        "Si tu étais une porte, je te claquerais toute la nuit.",
        "Je ne suis pas un photographe, mais je peux nous voir ensemble.",
        "Ton père doit être un terroriste, parce que tu es une bombe.",
        "Tu es tellement chaude que tu ferais fondre l'Antarctique.",
        "Si je t’offrais mon corps, tu l'accepterais ?",
        "Si tu étais un fruit, tu serais une belle pêche.",
        "J’ai perdu mon numéro de téléphone, je peux avoir le tien ?",
        "Tu as une carte ? Parce que je me suis perdu dans tes yeux.",
        "Je ne suis pas ivre, je suis juste intoxiqué par toi.",
        "Tes parents sont des voleurs, ils ont volé toutes les étoiles pour les mettre dans tes yeux.",
        "Je suis nouveau en ville, tu pourrais me montrer le chemin de ton cœur ?",
        "Si tu étais un hamburger, tu serais un McMignonne.",
        "Je ne suis pas astrologue, mais je peux lire notre avenir dans tes yeux.",
        "Es-tu un calendrier ? Parce que tu es tout ce que je veux voir.",
        "Tu dois être un balai, parce que tu as balayé mon cœur.",
        "Si tu étais un légume, tu serais une courgette... parce que tu me rends fou.",
        "Je ne suis pas un génie, mais je peux exaucer tes vœux.",
        "Si je pouvais réorganiser l'alphabet, je mettrais U et I ensemble.",
        "Es-tu un volcan ? Parce que tu fais monter la température.",
        "Ton père est un artiste ? Parce qu’il a fait un chef-d'œuvre.",
        "Je ne suis pas un jardinier, mais je ferais bien pousser notre amour.",
        "Es-tu un bonbon ? Parce que tu es sucrée à croquer.",
        "Je ne suis pas électricien, mais tu illumines ma vie.",
        "Je ne suis pas chirurgien, mais je veux te réparer le cœur.",
        "Si j'étais une mouche, je me poserais sur toi, parce que tu es du sucre.",
        "Es-tu une banane ? Parce que je te trouve à croquer.",
        "Je ne suis pas un boulanger, mais tu es un pain pour les yeux.",
        "Ton père est-il un extra-terrestre ? Parce que tu es hors de ce monde.",
        "Es-tu une décharge électrique ? Parce que tu m’électrifies.",
        "Je ne suis pas une fusée, mais tu me fais décoller.",
        "Je ne suis pas un scientifique, mais je suis en chimie avec toi.",
        "Es-tu un wifi ? Parce que je ressens une connexion.",
        "Je ne suis pas un pirate, mais je t'ai trouvé, mon trésor.",
        "Si tu étais une pizza, tu serais un régal.",
        "Je ne suis pas un pompier, mais tu mets le feu à mon cœur.",
        "Es-tu une illusion d'optique ? Parce que je ne peux pas te croire réelle.",
        "Je ne suis pas un nageur, mais je me noierais dans tes yeux.",
        "Es-tu un fantôme ? Parce que tu hantes mes rêves.",
        "Je ne suis pas un volcanologue, mais tu es en éruption dans mon cœur.",
        "Ton père est-il un parieur ? Parce qu'il a misé gros et a gagné.",
        "Es-tu un fouet ? Parce que tu fouettes mon cœur.",
        "Je ne suis pas un astronaute, mais je t'emmènerais bien sur la lune.",
        "Es-tu une étoile filante ? Parce que j'ai fait un vœu en te voyant.",
        "Je ne suis pas un fermier, mais tu es une perle rare.",
        "Es-tu un ouragan ? Parce que tu bouleverses ma vie.",
        "Je ne suis pas un boxeur, mais tu m'as mis K.O.",
        "Es-tu un cambrioleur ? Parce que tu as volé mon cœur.",
        "Je ne suis pas un poète, mais tu es mon inspiration.",
        "Es-tu une plage ? Parce que je me perds dans tes vagues.",
        "Je ne suis pas un chef, mais tu es mon plat préféré.",
        "Es-tu une abeille ? Parce que tu fais du miel avec mon cœur.",
        "Je ne suis pas un plombier, mais tu débordes mon cœur.",
        "Es-tu un éclair ? Parce que tu illumines ma vie.",
        "Je ne suis pas un marin, mais tu es mon port d'attache.",
        "Es-tu une étoile ? Parce que tu brilles dans ma vie.",
        "Je ne suis pas un tailleur, mais tu es taillée sur mesure pour moi.",
        "Es-tu un diamant ? Parce que tu es précieuse.",
        "Je ne suis pas un magicien, mais tu es mon sort préféré.",
        "Es-tu une chanson ? Parce que tu es la mélodie de mon cœur.",
        "Je ne suis pas un charpentier, mais tu as construit un pont vers mon cœur.",
        "Es-tu une flamme ? Parce que tu brûles en moi.",
        "Je ne suis pas un mathématicien, mais tu es l’équation de mon bonheur.",
        "Es-tu un rêve ? Parce que tu es trop belle pour être réelle.",
        "Je ne suis pas un alchimiste, mais tu es mon or.",
        "Es-tu une sirène ? Parce que tu m’attires avec ta voix.",
        "Je ne suis pas un jongleur, mais tu es mon numéro d’équilibriste.",
        "Es-tu un phare ? Parce que tu guides mon cœur.",
        "Je ne suis pas un guide touristique, mais tu es ma destination.",
        "Es-tu une vague ? Parce que tu me fais chavirer.",
        "Je ne suis pas un athlète, mais tu es ma médaille d’or.",
        "Es-tu un livre ? Parce que je ne peux pas m'arrêter de te lire.",
        "Je ne suis pas un ours, mais tu es mon hibernation.",
        "Es-tu une lumière ? Parce que tu éclaires ma vie.",
        "Je ne suis pas un miroir, mais tu es mon reflet.",
        "Es-tu une cloche ? Parce que tu sonnes mon cœur.",
        "Je ne suis pas un forgeron, mais tu as forgé mon cœur.",
        "Es-tu un trésor caché ? Parce que je te cherchais partout.",
        "Je ne suis pas un collectionneur, mais tu es ma pièce maîtresse.",
        "Es-tu une île ? Parce que tu es mon refuge.",
        "Je ne suis pas un photographe, mais tu es mon cliché préféré.",
        "Es-tu une pierre précieuse ? Parce que tu es inestimable.",
        "Je ne suis pas un cartographe, mais tu es ma carte au trésor.",
        "Es-tu un arc-en-ciel ? Parce que tu apportes de la couleur à ma vie.",
        "Je ne suis pas un danseur, mais tu es ma partenaire idéale.",
        "Es-tu un parfum ? Parce que tu envoûtes mes sens.",
        "Je ne suis pas un berger, mais tu es ma brebis égarée.",
        "Es-tu un ticket gagnant ? Parce que tu es ma chance.",
        "Je ne suis pas un poing, mais tu frappes fort dans mon cœur.",
        "Es-tu un éclat de soleil ? Parce que tu réchauffes ma vie.",
        "Je ne suis pas un prince, mais tu es ma princesse.",
        "Es-tu un instrument ? Parce que tu joues la mélodie de mon cœur.",
        "Je ne suis pas un peintre, mais tu es mon chef-d'œuvre.",
        "Es-tu une princesse ? Parce que tu règnes sur mon cœur.",
        "Je ne suis pas un guerrier, mais tu es mon combat.",
        "Es-tu une fée ? Parce que tu exauces mes rêves.",
        "Je ne suis pas un diamant, mais tu es ma pierre précieuse.",
        "Es-tu une sirène ? Parce que tu fais chavirer mon cœur.",
        "Je ne suis pas un collectionneur, mais tu es mon trésor."
    ];

    if (generatedDate.length == beauf.length) {
        generatedDate = [];
    }

    var choice;
    do {
        choice = Math.floor(Math.random() * beauf.length);
    } while (generatedDate.includes(choice));

    generatedDate.push(choice);

    if (choice >= 0 && choice < beauf.length) {
        return beauf[choice];
    } else {
        return "You're juste en assohole, go to work.";
    }
}